---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: setup-go
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - id: run-tests
        name: Run go tests
        run: go test -v -short ./...
      - id: import-gpg
        name: Import GPG key
        if: ${{ success() }}
        uses: hashicorp/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - id: docker-login
        name: Login to Docker hub
        if: ${{ success() }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - id: goreleaser
        name: Run GoReleaser
        if: ${{ success() }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import-gpg.outputs.fingerprint }}
