# Stale issue and PR workflow
---
name: stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-close: -1
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not
            had recent activity. It will be closed if no further activity
            occurs.
            Thank you for your contributions.
          close-issue-label: wontfix
          close-issue-message: >
            This issue has been automatically closed because it has been marked
            as stale for 7 days with no activity. Thank you for your
            contributions.
